To_Do/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("tasks.urls")),
    path("user/",include("user.urls")),
]

tasks/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "tasks"

urlpatterns = [
    path("",views.index,name="index"),
    path("updatetask/<str:id>/",views.updateTask,name="update_task"),
    path("delete_task<str:id>/",views.deleteTask,name="delete_task"),
    path("completed",views.complededTasks,name="completed_tasks"),
]

user/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from . views import *

app_name = "user"

urlpatterns = [
    path("register/",registerPage,name="register"),
    path("login/",loginPage,name="login"),
    path("logout/",logoutPage,name="logout"),
]

tasks/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.contrib.auth.models import User
# Create your models here.
class Task(models.Model):
    author = models.ForeignKey(User ,on_delete=models.CASCADE ,null=True ,verbose_name="Yazan:",blank=True ,default=None)
    title = models.TextField(verbose_name="Basliq:")
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Yazilma Tarixi:")
    confirm = models.BooleanField(default=False,verbose_name="Tamamlanilib?:")
    def __str__(self):
        return self.title

user/models.py
from django.db import models

# Create your models here.

tasks/forms.py
from django import forms
from django.db.models import fields
from django.forms import ModelForm, widgets
from . import models

# Forms
class TaskForm(forms.ModelForm):
    class Meta:
        model = models.Task
        widgets = {
            'title': forms.Textarea(attrs={'class':'addbar','spellcheck':'false','cols':81,'rows':4,'style':'resize:none;'}),
        }
        fields = "__all__"
        

user/forms.py
from django.forms.forms import Form
from tasks.views import deleteTask
from django import forms
from django.db.models import fields
from django.forms import ModelForm, widgets
from django.forms.fields import CharField
from . import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):

    password1 = CharField(
        widget=forms.PasswordInput(attrs={'class':'passfields','style':'text-align:center; margin-left:100px; width:75%; border-radius:3px;'})
    )
    password2 = CharField(
        widget=forms.PasswordInput(attrs={'class':'passfields','style':'text-align:center; margin-left:100px; width:75%; border-radius:3px;'})
    )

    class Meta(UserCreationForm.Meta):
        model = User
        widgets = {
            'username': forms.TextInput(attrs={'class':'fields'}),
            'email': forms.TextInput(attrs={'class':'fields'}),
        }
        
        fields = ["password1","password2","username","email"]


class LoginForm(forms.Form):
    username = forms.CharField(required=True,widget=forms.TextInput(attrs={
        'class':"login-fields"
    }))
    password = forms.CharField(required=True,widget=forms.PasswordInput(attrs={
        "class":"login-fields"
    }))

tasks/views.py
from django.shortcuts import render,redirect
from . import models
from .forms import *
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required(login_url="user:login")
def index(request):
    tasks = models.Task.objects.filter(confirm="False",author=request.user).order_by('-id')
    form = TaskForm()

    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid:
            instance=form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect("/")
    context = {
        "tasks":tasks,
        "form":form,
    }
    return render(request,"index.html",context)


@login_required(login_url="user:login")
def updateTask(request,id):
    task = models.Task.objects.get(id=id)
    form = TaskForm(instance=task)

    if request.user == task.author:
        if request.method == "POST":
            form = TaskForm(request.POST,instance=task)
            if form.is_valid:
                form.save()
                return redirect("/")
    else:
        raise ValueError("Bu Task Sizin Deyil!")
    context = {
        "form":form,
    }
    return render(request,"update_task.html",context)

@login_required(login_url="user:login")
def deleteTask(request,id):
    task = models.Task.objects.get(id=id)
    
    if request.user == task.author:
        task.delete()
        return redirect("/")
    else:
        raise ValueError("Bu Task Sizin Deyil!")

    context = {
        "task":task,
    }
    return render(request,"delete_task.html",context)

@login_required(login_url="user:login")
def complededTasks(request):
    tasks = models.Task.objects.filter(confirm="True",author=request.user)

    context = {
        "tasks":tasks,
    }

    return render(request,"completeds.html",context)

user/views.py
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render,redirect
from .forms import *
# Create your views here.

def registerPage(request):
    form = RegisterForm()
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("tasks:index")

    context = {"form":form}
    return render(request,"register.html",context)


def loginPage(request):
    form = LoginForm()
    if request.method == "POST":
        form = LoginForm(request.POST)
        username = request.POST.get("username")
        password = request.POST.get("password")
        
        account = authenticate(username=username,password=password)
        if account is None:
            raise ValidationError(request,"Parol Ya Da Istifadeci Adi Uygun Deyil!")
        else:
            login(request,account)
            return redirect("tasks:index")

    context = {
        "form":form,
    }
    return render(request,"login.html",context)


def logoutPage(request):
    logout(request)
    return redirect("tasks:index")

templates/completeds.html
{% extends 'layout.html' %}


{% block body %}
<div>
    <link rel="stylesheet" href="static/css/style2.css">
    <h3 style="display: inline; margin-right: 380px;">Tamamlanmislar</h3>
    <a class="btn-sm btn-warning taskbutton" href="/">
        <i class="fas fa-tasks taskicon" style="padding: 10px; padding-top: 30px; padding-bottom: 30px;">
            Tasklar
        </i>
    </a>

    {% if tasks %}
    {% for task in tasks %}
    <hr>
    <span><del>{{task.title}}</del></span><br>
    <a href="{% url 'tasks:update_task' task.id %}" class="btn btn-info btn-sm">Guncelle</a>
    <a href="{% url 'tasks:delete_task' task.id %}" class="btn btn-danger btn-sm">Sil</a>
    {% endfor %}
    {% else %}
    <hr>
    <div class="alert alert-info" style="text-align:center;">
    Tamamlanmis Task Yoxdur. Tasklarini Tamamlamaqa Calis :)
    </div>
    <hr><br><br>
    
    {% endif %}
</div>

{% endblock body %}

templates/delete_task.html
{% extends 'layout.html' %}

{% block body %}

{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To-Do</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />

    <style>
        body {
            background: rgb(0,159,255);
            background: linear-gradient(90deg, rgba(0,159,255,1) 0%, rgba(236,47,75,1) 100%);
            font-family: 'Montserrat', sans-serif;
        }

        .container {
            max-width: 800px;
            margin-top: 100px;
            background-color: rgb(202, 202, 202);
            padding: 35px;
            height: 500px;
            border-radius: 10px;
            -webkit-box-shadow: 5px 3px 5px 0px rgba(50, 50, 50, 0.75);
            -moz-box-shadow: 5px 3px 5px 0px rgba(50, 50, 50, 0.75);
            box-shadow: 5px 3px 5px 0px rgba(50, 50, 50, 0.75);
            overflow-y: scroll;
        }

        .container::-webkit-scrollbar {
            display: none;
        }
    </style>

</head>

<body>

    <div class="container">
        {% block body %}

        {% endblock body %}
    </div>



    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
</body>

</html>

templates/login.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}
<h3 style="display: inline; margin-right: 340px; margin-left: 100px;">Giris Et</h3>

<hr>
<link rel="stylesheet" href="{% static 'css/style4.css' %}">
{% if form.errors %}
<div class="alert alert-danger outter-error">
    <div class="error-fields">
        <h4>Please fix the following errors</h4>
        <ul>
            {% for field in form %}
            {% if field.errors %}
            {% for error in field.errors %}
            <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
            {% endfor %}
            {% endif %}
            {% endfor %}
        </ul>
    </div>
    {% if form.non_field_errors %}
    {{ form.non_field_errors }}
    {% endif %}
</div>
{% endif %}

<link rel="stylesheet" type="text/css" href="{% static 'css/style5.css' %}">
<form action="" method="post">
    {% csrf_token %}
    <hr>
    <span style="margin-left:100px;">Istifadeci Adi:</span>
    <br>
    {{form.username}}
    <hr>
    <span style="margin-left:100px;">Parol:</span>
    <br>
    {{form.password}}
    <hr>
    <button type="submit" class="btn-block btn-group-sm btn-info subbut h5">Giris Et</button>
    <hr>
    <div class="small" style="text-align: center;">
        Hesabiniz Yoxdur? <a href="{% url 'user:register' %}">Qeydiyatdan Kec</a>
    </div>
    <hr>
</form>
{% endblock body %}

templates/logout.html
{% extends 'layout.html' %}

{% block body %}

{% endblock body %}

templates/register.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}
<link rel="stylesheet" href="{% static 'css/style4.css' %}">
    <h3 style="display: inline; margin-right: 380px;">Qeydiyatdan Kec</h3>
    <hr>
{% if form.errors %}
<div class="alert alert-danger outter-error">
    <div class="error-fields">
        <h4>Please fix the following errors</h4>
        <ul>
            {% for field in form %}
            {% if field.errors %}
            {% for error in field.errors %}
            <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
            {% endfor %}
            {% endif %}
            {% endfor %}
        </ul>
    </div>
    {% if form.non_field_errors %}
    {{ form.non_field_errors }}
    {% endif %}
</div>
{% endif %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style3.css' %}">
<form action="" method="post">
    {% csrf_token %}
    Istifadeci Adi:
    <br>
    {{form.username}}
    <hr>
    Email:
    <br>
    {{form.email}}
    <hr>
    <span style="margin-left:100px;">Parol:</span>
    <br>
    {{form.password1}}
    <hr>
    <span style="margin-left:100px;">Parol Dogrula:</span>
    <br>
    {{form.password2}}
    <hr>
    <button type="submit" class="btn-block btn-group-sm btn-info subbut h5">Qeydiyatdan Kec</button>
    <div class="small" style="text-align: center;">
        Hesabiniz Var? <a href="{% url 'user:login' %}">Giris Et</a>
    </div>
    <hr>
</form>

{% endblock body %}

templates/update_task.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}
<link rel="stylesheet" href="{% static 'css/style7.css' %}">
<h3>Edit To-Do</h3>
<hr>
<form method="POST" action="">
{% csrf_token %}
Basliq:
<br>
{{form.title}}
Tamamlanib?:
{{form.confirm}}
<hr>

<input class="btn-danger btn-sm btn-block" type="submit" value="Bitdi!">
<hr>
</form>
{% endblock body %}